DROP TABLE IF EXISTS WEATHER;

CREATE TABLE WEATHER (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    CITY_NAME VARCHAR(50) NOT NULL,
    COUNTRY_CODE VARCHAR(2) NOT NULL,
    DESCRIPTION VARCHAR(255) NOT NULL,
    LAST_UPDATED TIMESTAMP NOT NULL,
    PRIMARY KEY (ID)
);

CREATE INDEX idx_city_country ON WEATHER(CITY_NAME, COUNTRY_CODE);
